In [2]:
import math
import numpy as np
from scipy.stats import norm

In [18]:
mu = np.matrix([[0.08],[0.10],[0.10],[0.14]])

In [19]:
sigma_a =  np.array([0.12,0.12,0.15,0.20])
sigma = np.matrix([[0.12],[0.12],[0.15],[0.20]])

In [20]:
R = np.matrix([[1,0.2,0.5,0.3],[0.2,1,0.7,0.4],[0.5,0.7,1,0.9],[0.3,0.4,0.9,1]])

In [9]:
#np.diag only works with arrays
S = np.diag(sigma_a)
S

array([[0.12, 0.  , 0.  , 0.  ],
       [0.  , 0.12, 0.  , 0.  ],
       [0.  , 0.  , 0.15, 0.  ],
       [0.  , 0.  , 0.  , 0.2 ]])

In [10]:
Epsilon = S * R * S
Epsilon

matrix([[0.0144 , 0.00288, 0.009  , 0.0072 ],
        [0.00288, 0.0144 , 0.0126 , 0.0096 ],
        [0.009  , 0.0126 , 0.0225 , 0.027  ],
        [0.0072 , 0.0096 , 0.027  , 0.04   ]])

In [12]:
UV = np.matrix([[1],[1],[1],[1]])

In [13]:
A = np.transpose(UV) * np.linalg.inv(Epsilon) * UV
A

matrix([[456.52173913]])

In [14]:
B = np.transpose(mu) * np.linalg.inv(Epsilon) * UV
B

matrix([[63.81642512]])

In [15]:
C = np.transpose(mu) * np.linalg.inv(Epsilon) * mu
C

matrix([[9.38969404]])

In [17]:
lambda1 = ((A*0.1)-B)/(A*C-np.square(B))
lambda1

matrix([[-0.08485456]])

In [21]:
gamma1 = (C-(B*0.1))/(A*C-np.square(B))
gamma1

matrix([[0.01405216]])

In [33]:
# w_star =  np.asscalar(lambda1) * mu --> np.asscalar retired, replaced by .item() attribute
w_star = (np.linalg.inv(Epsilon)) * ((lambda1.item() * mu)+(gamma1.item() * UV ))
w_star

matrix([[ 0.76228686],
        [ 0.84419926],
        [-0.98762956],
        [ 0.38114343]])

# Exercice 2

In [34]:
Epsilon_2 = np.matrix([[9,3,0],[3,16,5],[0,5,25]])
Epsilon_2

matrix([[ 9,  3,  0],
        [ 3, 16,  5],
        [ 0,  5, 25]])

In [35]:
np.linalg.inv(Epsilon_2)

matrix([[ 0.11904762, -0.02380952,  0.0047619 ],
        [-0.02380952,  0.07142857, -0.01428571],
        [ 0.0047619 , -0.01428571,  0.04285714]])

In [44]:
test_matrix = (1/210)*(np.matrix([[25,-5,1],[-5,15,-3],[1,-3,9]]))
test_matrix

matrix([[ 0.11904762, -0.02380952,  0.0047619 ],
        [-0.02380952,  0.07142857, -0.01428571],
        [ 0.0047619 , -0.01428571,  0.04285714]])

In [48]:
np.linalg.inv(Epsilon_2) == test_matrix

matrix([[False, False, False],
        [False, False,  True],
        [False, False,  True]])

# Exercise 3

In [50]:
#Tangency portfolio
# it's asset allocation w_t
r = 0.05
w_t = (np.linalg.inv(Epsilon) * (mu - (r * UV))) / (B - A*r)
w_t

matrix([[ 0.93891181],
        [ 1.66470242],
        [-3.35376154],
        [ 1.75014732]])

In [51]:
m_t = (C - B*r) / (B - A*r) #its return
m_t

matrix([[0.15122766]])

In [52]:
st_dev_t = np.sqrt((C - 2*B*r + A*np.square(r)) / np.square(B - A*r))
st_dev_t

matrix([[0.04969456]])

In [57]:
P = ((m_t - r)/st_dev_t)
norm.cdf(P)

array([[0.97917482]])

# Exercise 4

In [61]:
import matplotlib.pyplot as plt
%matplotlib inline

In [63]:
assets = ['A','B']
r_4 = 0.05
mu_4 = np.matrix([[0.1],[0.2]])
st_dev_4 = np.matrix([[0.2],[0.3]])