In [2]:
import math
import numpy as np
from scipy.stats import norm

In [18]:
mu = np.matrix([[0.08],[0.10],[0.10],[0.14]])

In [19]:
sigma_a =  np.array([0.12,0.12,0.15,0.20])
sigma = np.matrix([[0.12],[0.12],[0.15],[0.20]])

In [20]:
R = np.matrix([[1,0.2,0.5,0.3],[0.2,1,0.7,0.4],[0.5,0.7,1,0.9],[0.3,0.4,0.9,1]])

In [9]:
#np.diag only works with arrays
S = np.diag(sigma_a)
S

array([[0.12, 0.  , 0.  , 0.  ],
       [0.  , 0.12, 0.  , 0.  ],
       [0.  , 0.  , 0.15, 0.  ],
       [0.  , 0.  , 0.  , 0.2 ]])

In [10]:
Epsilon = S * R * S
Epsilon

matrix([[0.0144 , 0.00288, 0.009  , 0.0072 ],
        [0.00288, 0.0144 , 0.0126 , 0.0096 ],
        [0.009  , 0.0126 , 0.0225 , 0.027  ],
        [0.0072 , 0.0096 , 0.027  , 0.04   ]])

In [12]:
UV = np.matrix([[1],[1],[1],[1]])

In [13]:
A = np.transpose(UV) * np.linalg.inv(Epsilon) * UV
A

matrix([[456.52173913]])

In [14]:
B = np.transpose(mu) * np.linalg.inv(Epsilon) * UV
B

matrix([[63.81642512]])

In [15]:
C = np.transpose(mu) * np.linalg.inv(Epsilon) * mu
C

matrix([[9.38969404]])

In [17]:
lambda1 = ((A*0.1)-B)/(A*C-np.square(B))
lambda1

matrix([[-0.08485456]])

In [21]:
gamma1 = (C-(B*0.1))/(A*C-np.square(B))
gamma1

matrix([[0.01405216]])

In [33]:
# w_star =  np.asscalar(lambda1) * mu --> np.asscalar retired, replaced by .item() attribute
w_star = (np.linalg.inv(Epsilon)) * ((lambda1.item() * mu)+(gamma1.item() * UV ))
w_star

matrix([[ 0.76228686],
        [ 0.84419926],
        [-0.98762956],
        [ 0.38114343]])